# Generated by Django 4.2.1 on 2023-07-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('doi', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='movie/images/')),
            ],
        ),
    ]
